namespace EF6MigrationSugar.DataAccess.Generators
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.Migrations.Design;
    using System.Data.Entity.Migrations.Model;
    using System.Data.Entity.Migrations.Utilities;

    /// <summary>
    /// A custom migration code generator used to generate the c# code when add-migration has been called
    /// </summary>
    internal class CustomMigrationCodeGenerator : CSharpMigrationCodeGenerator
    {
        protected override void WriteClassStart(
            string @namespace, 
            string className, 
            IndentedTextWriter writer,
            string @base, 
            bool designer = false, 
            IEnumerable<string> namespaces = null)
        {
            writer.WriteLine($"// Generated Time: {DateTime.Now}");
            writer.WriteLine($"// Generated By: {Environment.UserName}");
            writer.WriteLine();

            base.WriteClassStart(@namespace, className, writer, @base, designer, namespaces);
        }

        protected override void Generate(CreateTableOperation createTableOperation, IndentedTextWriter writer)
        {
            writer.WriteLine($"// Generate {createTableOperation.Name} table:");

            base.Generate(createTableOperation, writer);
        }
    }
}
