// Generated Time: 26.2.2018 г. 20:14:46
// Generated By: dimitar.mitev

namespace EF6MigrationSugar.DataAccess.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class CreateDB : DbMigration
    {
        public override void Up()
        {
            // Generate dbo.Movies table:
            CreateTable(
                "dbo.Movies",
                c => new
                    {
                        Id = c.Guid(nullable: false, identity: true),
                        Title = c.String(nullable: false, maxLength: 200),
                        ReleaseDate = c.DateTime(nullable: false),
                        Genre = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.Id)
                .Index(t => t.Title, unique: true);
            
        }
        
        public override void Down()
        {
            DropIndex("dbo.Movies", new[] { "Title" });
            DropTable("dbo.Movies");
        }
    }
}
